name: CI Java (todas las ramas)

on:
  push:          # corre en cualquier rama
  pull_request:  # corre en cualquier PR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 17 + cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build & Test (Maven)
        run: mvn -B -ntp clean verify
